defaults: &defaults
  app_title: Taradai
  activity_feed_limit: 40
  languages: ['es', 'en']
  
  assets:  'http://assets.taradai.com/'
  assets1: 'http://assets1.taradai.com/files/'
  assets2: 'http://assets2.taradai.com/files/'
  assets3: 'http://assets3.taradai.com/files/'
  assets4: 'http://assets4.taradai.com/files/'
  
  temporal_storage_photos_pre_queue: "/mnt/fs/a1/tmp"

  redis_server: "192.168.0.221"
  redis_port: 6379
  
  mogile_trackers: ['192.168.2.221:7001', '192.168.2.222:7001']
  mogile_domain: 'tests'
  
  mail_from: 'taradai<antoniofernandezvara@gmail.com>'
  mail_url: 'localhost:3000'
  
development:
    <<: *defaults
    redis_activity_last_id_expire: 86400
test:
    <<: *defaults
production:
    <<: *defaults